config:
  target: 'http://localhost:3002'
  phases:
    - duration: 60
      arrivalRate: 1000
  # payload:
  #   path: './database/ikea_seed_pg.csv'
  #   fields:
  #     - 'name'
  #   skipHeader: true
scenarios:
  - flow:
      - get:
          url: '/searchbar/z'
          # url: '/searchbar/{{ name }}'
